import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Login from "./login";
import Homepage from "./homepage";

const Home: NextPage = (props) => {
  const { status } = useSession();

  return (
    <>
      <Head>
        <title>Filelogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {status === "authenticated" ? <Homepage /> : <Login />}
    </>
  );
};

export default Home;
