import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Login from "./login";
import Admin from "./admin/admin";
import Homepage from "./homepage";
import Loading from "~/components/loading";

const Home: NextPage = () => {
  const { status, data } = useSession();

  if (status === "loading") {
    return <Loading />;
  }

  return (
    <>
      <Head>
        <title>Filelogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {status === "authenticated" ? (
        data.user.role.title === "Admin" ? (
          <Admin />
        ) : (
          <Homepage />
        )
      ) : (
        <Login />
      )}
    </>
  );
};

export default Home;
